"""
Reel download manager using yt-dlp.

Downloads reel videos from Instagram URLs to local storage
in the best available quality. Extracts caption & hashtags
from yt-dlp metadata and updates the reel tracking DB.
"""

from __future__ import annotations

import asyncio
import json
import re
import threading
import time
from pathlib import Path
from typing import Optional, Tuple

from .config import StorageSettings
from .instagram_client import ReelInfo
from .logger import get_logger

log = get_logger("downloader")

_COOKIES_DIR = Path("./cookies")

# Lock to prevent concurrent cookie file writes from multiple workers
_cookie_lock = threading.Lock()


class ReelDownloader:
    """Downloads Instagram reels using yt-dlp."""

    def __init__(self, storage: StorageSettings, login_user: str = "") -> None:
        self.storage = storage
        self._download_dir = Path(storage.local_dir)
        self._download_dir.mkdir(parents=True, exist_ok=True)
        self._login_user = login_user
        self._netscape_cookie_file = _COOKIES_DIR / "cookies.txt"

    async def close(self) -> None:
        pass

    async def download(self, reel: ReelInfo) -> Tuple[str, str, list, int]:
        """Download a reel and return (file_path, caption, hashtags, view_count).

        Uses yt-dlp which reliably extracts video + metadata.
        The view_count comes from yt-dlp's metadata extraction during download.
        """
        safe_name = self._safe_filename(reel)
        dest = self._download_dir / safe_name

        if dest.exists() and dest.stat().st_size > 0:
            log.info("Already downloaded, skipping: %s", dest.name)
            return str(dest), reel.caption, reel.hashtags, reel.view_count

        # Try yt-dlp (extracts video + caption + metadata + view count)
        try:
            return await self._download_ytdlp(reel, dest)
        except Exception as exc:
            log.warning("yt-dlp failed for %s: %s – trying direct URL", reel.shortcode, exc)

        # Fallback: direct URL download (no view count available)
        if reel.video_url:
            path = await self._download_direct(reel, dest)
            return path, reel.caption, reel.hashtags, 0

        raise RuntimeError(f"Cannot download reel {reel.shortcode}: no video URL available")

    def _make_netscape_cookies(self) -> Optional[str]:
        """Convert SeleniumBase JSON cookies → Netscape cookie.txt for yt-dlp.
        
        Thread-safe: uses a lock to prevent concurrent writes corrupting the file.
        """
        json_file = _COOKIES_DIR / f"{self._login_user or 'anon'}_cookies.json"
        if not json_file.exists():
            log.debug("No cookie file at %s", json_file)
            return None
        try:
            with _cookie_lock:
                with open(json_file, "r", encoding="utf-8") as fh:
                    cookies = json.load(fh)
                if not cookies:
                    return None

                lines = ["# Netscape HTTP Cookie File", "# Generated by insta_monitor"]
                for c in cookies:
                    domain = c.get("domain", ".instagram.com")
                    include_sub = "TRUE" if domain.startswith(".") else "FALSE"
                    path = c.get("path", "/")
                    secure = "TRUE" if c.get("secure", False) else "FALSE"
                    expiry = str(int(c.get("expiry", c.get("expirationDate", time.time() + 86400 * 365))))
                    name = c.get("name", "")
                    value = c.get("value", "")
                    lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

                self._netscape_cookie_file.parent.mkdir(parents=True, exist_ok=True)
                with open(self._netscape_cookie_file, "w", encoding="utf-8") as fh:
                    fh.write("\n".join(lines) + "\n")
                log.info("🍪 Wrote %d cookies to %s for yt-dlp", len(cookies), self._netscape_cookie_file.name)
                return str(self._netscape_cookie_file)
        except Exception as exc:
            log.warning("Failed to convert cookies for yt-dlp: %s", exc)
            return None

    async def _download_ytdlp(self, reel: ReelInfo, dest: Path) -> Tuple[str, str, list, int]:
        """Download using yt-dlp. Returns (path, caption, hashtags, view_count)."""
        import yt_dlp  # type: ignore

        url = reel.permalink or f"https://www.instagram.com/reel/{reel.shortcode}/"

        ydl_opts = {
            "outtmpl": str(dest.with_suffix(".%(ext)s")),
            "format": "best[ext=mp4]/best",
            "quiet": True,
            "no_warnings": True,
            "merge_output_format": "mp4",
            "socket_timeout": 30,
            "retries": 3,
        }

        # Pass cookies for authenticated access
        cookie_path = self._make_netscape_cookies()
        if cookie_path:
            ydl_opts["cookiefile"] = cookie_path
            log.info("Using cookies for yt-dlp download of %s", reel.shortcode)

        loop = asyncio.get_running_loop()

        extracted_caption = ""
        extracted_hashtags: list = []
        extracted_view_count: int = 0

        def _do_download():
            nonlocal extracted_caption, extracted_hashtags, extracted_view_count
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=True)
                if info:
                    # Extract caption / description
                    desc = info.get("description", "") or ""
                    title = info.get("title", "") or ""
                    extracted_caption = desc if desc else title
                    # Extract hashtags from caption
                    extracted_hashtags = re.findall(r'#\w+', extracted_caption)
                    # Extract real view count from metadata
                    extracted_view_count = info.get("view_count", 0) or 0
                    log.info(
                        "📊 yt-dlp metadata for %s: view_count=%s, like_count=%s",
                        reel.shortcode,
                        info.get("view_count", "N/A"),
                        info.get("like_count", "N/A"),
                    )
                    filename = ydl.prepare_filename(info)
                    return filename
                return str(dest)

        result_path = await loop.run_in_executor(None, _do_download)

        result = Path(result_path)
        if result.exists():
            if result != dest and result.suffix == ".mp4":
                final = dest.with_suffix(".mp4")
                if final != result:
                    result.rename(final)
                    result = final
            log.info(
                "Downloaded via yt-dlp: %s (%.2f MB) | %d real views",
                result.name,
                result.stat().st_size / (1024 * 1024),
                extracted_view_count,
            )
            if extracted_caption:
                log.info("  Caption: %.100s", extracted_caption)
            if extracted_hashtags:
                log.info("  Hashtags: %s", " ".join(extracted_hashtags[:10]))
            return str(result), extracted_caption, extracted_hashtags, extracted_view_count

        # Check for any file matching the pattern
        for f in self._download_dir.glob(f"{dest.stem}*"):
            if f.stat().st_size > 0:
                log.info("Downloaded via yt-dlp: %s", f.name)
                return str(f), extracted_caption, extracted_hashtags, extracted_view_count

        raise FileNotFoundError(f"yt-dlp did not produce output file for {reel.shortcode}")

    async def _download_direct(self, reel: ReelInfo, dest: Path) -> str:
        """Download directly from the CDN video URL."""
        import aiohttp

        log.info("Downloading reel %s via direct URL …", reel.shortcode)
        timeout = aiohttp.ClientTimeout(total=300)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.get(reel.video_url) as resp:
                resp.raise_for_status()
                tmp = dest.with_suffix(".tmp")
                total = 0
                with open(tmp, "wb") as fh:
                    async for chunk in resp.content.iter_chunked(64 * 1024):
                        fh.write(chunk)
                        total += len(chunk)

                final = dest.with_suffix(".mp4")
                tmp.rename(final)

        size_mb = total / (1024 * 1024)
        log.info("Downloaded reel %s (%.2f MB) → %s", reel.shortcode, size_mb, final.name)
        return str(final)

    @staticmethod
    def _safe_filename(reel: ReelInfo) -> str:
        """Generate a consistent filename: username_shortcode.mp4"""
        safe_user = re.sub(r"[^\w]", "_", reel.username or "unknown")
        safe_code = re.sub(r"[^\w]", "_", reel.shortcode)
        return f"{safe_user}_{safe_code}.mp4"
